# Generated by Django 4.2.7 on 2023-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour_guide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
